# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8eef02fea2d3c3d5d1a33dcc4265d35e628fc6b1ba022aea5970939c0b44f7beebbfef55efdfa69f67a8727a6d7d66ad11673bc39e8beb1f4708c085c00d98fb

test:
  secret_key_base: aa5c49d2148912aa281eee297a8d7136656c6694021b5aef1f94d01f74860de4420a8ccc9b6a97ad4346bf6ca945df14ff92782ee46636534daf0291b1a4dd85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
